package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer id;
	private Farmer farmer;
	private Product product;
	private int quantity;
	private float total;

	public Cart() {
	}

	public Cart(Farmer farmer, Product product, int quantity, float total) {
		this.farmer = farmer;
		this.product = product;
		this.quantity = quantity;
		this.total = total;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

}
