package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String category;
	private Set machinaries = new HashSet(0);

	public Category() {
	}

	public Category(String category) {
		this.category = category;
	}

	public Category(String category, Set machinaries) {
		this.category = category;
		this.machinaries = machinaries;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getMachinaries() {
		return this.machinaries;
	}

	public void setMachinaries(Set machinaries) {
		this.machinaries = machinaries;
	}

}
