package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private String mobile;
	private String email;
	private String comment;

	public Contact() {
	}

	public Contact(String mobile, String email, String comment) {
		this.mobile = mobile;
		this.email = email;
		this.comment = comment;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
