package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

/**
 * Demo generated by hbm2java
 */
public class Demo implements java.io.Serializable {

	private Integer demoId;
	private Farmer farmer;
	private Machinary machinary;
	private String address;
	private String mobile;
	private String date;

	public Demo() {
	}

	public Demo(Farmer farmer, Machinary machinary, String address, String mobile, String date) {
		this.farmer = farmer;
		this.machinary = machinary;
		this.address = address;
		this.mobile = mobile;
		this.date = date;
	}

	public Integer getDemoId() {
		return this.demoId;
	}

	public void setDemoId(Integer demoId) {
		this.demoId = demoId;
	}

	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	public Machinary getMachinary() {
		return this.machinary;
	}

	public void setMachinary(Machinary machinary) {
		this.machinary = machinary;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
