package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private ProductType productType;
	private byte[] productImg;
	private String productName;
	private String productDescription;
	private int price;
	private int stockQty;
	private Set carts = new HashSet(0);
	private Set purchases = new HashSet(0);

	public Product() {
	}

	public Product(ProductType productType, byte[] productImg, String productName, String productDescription, int price,
			int stockQty) {
		this.productType = productType;
		this.productImg = productImg;
		this.productName = productName;
		this.productDescription = productDescription;
		this.price = price;
		this.stockQty = stockQty;
	}

	public Product(ProductType productType, byte[] productImg, String productName, String productDescription, int price,
			int stockQty, Set carts, Set purchases) {
		this.productType = productType;
		this.productImg = productImg;
		this.productName = productName;
		this.productDescription = productDescription;
		this.price = price;
		this.stockQty = stockQty;
		this.carts = carts;
		this.purchases = purchases;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	public byte[] getProductImg() {
		return this.productImg;
	}

	public void setProductImg(byte[] productImg) {
		this.productImg = productImg;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getStockQty() {
		return this.stockQty;
	}

	public void setStockQty(int stockQty) {
		this.stockQty = stockQty;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set purchases) {
		this.purchases = purchases;
	}

}
