package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase implements java.io.Serializable {

	private Integer purchaseId;
	private Farmer farmer;
	private Product product;
	private Date purchaseDate;
	private int qty;
	private float total;
	private String address;
	private String mobile;

	public Purchase() {
	}

	public Purchase(Farmer farmer, Product product, Date purchaseDate, int qty, float total, String address,
			String mobile) {
		this.farmer = farmer;
		this.product = product;
		this.purchaseDate = purchaseDate;
		this.qty = qty;
		this.total = total;
		this.address = address;
		this.mobile = mobile;
	}

	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
