package com.pojo;
// Generated 22 May, 2018 11:41:46 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * SoilTest generated by hbm2java
 */
public class SoilTest implements java.io.Serializable {

	private Integer testId;
	private Farmer farmer;
	private Date testDate;
	private String address;
	private String mobile;

	public SoilTest() {
	}

	public SoilTest(Farmer farmer, Date testDate, String address, String mobile) {
		this.farmer = farmer;
		this.testDate = testDate;
		this.address = address;
		this.mobile = mobile;
	}

	public Integer getTestId() {
		return this.testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
